// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8mJ1_jqNQXQ9blpYs_4q8pYxvXKHfjo0',
    appId: '1:282443662860:web:987ef8e61416a574e89029',
    messagingSenderId: '282443662860',
    projectId: 'velisse-f6ff3',
    authDomain: 'velisse-f6ff3.firebaseapp.com',
    storageBucket: 'velisse-f6ff3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxI9uU01TMgi8ie31XbUfXaxn42HAPgsM',
    appId: '1:282443662860:android:9db6561dc9684c85e89029',
    messagingSenderId: '282443662860',
    projectId: 'velisse-f6ff3',
    storageBucket: 'velisse-f6ff3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt3XoSmGpMJs9Z9XHrYm7IsFb3ZTpxF_0',
    appId: '1:282443662860:ios:1d0796a7fabbcf5ae89029',
    messagingSenderId: '282443662860',
    projectId: 'velisse-f6ff3',
    storageBucket: 'velisse-f6ff3.firebasestorage.app',
    iosBundleId: 'com.example.velisse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt3XoSmGpMJs9Z9XHrYm7IsFb3ZTpxF_0',
    appId: '1:282443662860:ios:1d0796a7fabbcf5ae89029',
    messagingSenderId: '282443662860',
    projectId: 'velisse-f6ff3',
    storageBucket: 'velisse-f6ff3.firebasestorage.app',
    iosBundleId: 'com.example.velisse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8mJ1_jqNQXQ9blpYs_4q8pYxvXKHfjo0',
    appId: '1:282443662860:web:66fe621dbd2957e3e89029',
    messagingSenderId: '282443662860',
    projectId: 'velisse-f6ff3',
    authDomain: 'velisse-f6ff3.firebaseapp.com',
    storageBucket: 'velisse-f6ff3.firebasestorage.app',
  );
}
